version: "3.8"

services:
  api:
<<<<<<< HEAD
    build: ./api
    container_name: api-inmobiliaria
    restart: always
    env_file: ./api/.env
    expose:
      - "3001"
=======
    build: .
    container_name: api-inmobiliaria
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
>>>>>>> b280c7d2202ae18a198e4b6060afdf62386be0ae
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb-inmo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: inmobiliaria
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

<<<<<<< HEAD
  web:
    image: nginx:latest
    container_name: nginx-inmo
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

=======
>>>>>>> b280c7d2202ae18a198e4b6060afdf62386be0ae
volumes:
  mariadb_data:
