version: "3.8"

services:
  api:
    build: .
    container_name: api-inmobiliaria
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb-inmo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: inmobiliaria
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
